### ISSUE TITLE
eldoc support

### ISSUE THREAD

**Issue by nam3less** [emacs-php/phpactor.el#101]
Are there plans for phpactor to support eldoc?

**Comment by kermorgant** [comment]
I just had a look at eldoc, thanks for bringing that up.

It might be that phpactor's "hover" rpc action could be appropriate for that. I'll have a look into that.

**Comment by kermorgant** [comment]
@nam3less phpactor's `hover` function has a bit broader scope than just showing function arguments (it can also show FQN of a class for example).

you can see a screenshot of how it works with vim [here](https://github.com/phpactor/phpactor/pull/619)

So not sure if eldoc is the most appropriate but it's certainly worth a try. I hope to find time in coming weeks.

**Comment by kermorgant** [comment]
@nam3less available on develop (see README for configuration)
