### ISSUE TITLE
Eldoc integration is broken

### ISSUE THREAD

**Issue by zilti** [emacs-php/phpactor.el#138]
Enabling eldoc support as described in the readme results in constant errors:

```
eldoc error: (json-string-format doesn't start with `"'!)
```

**Comment by zilti** [comment]
Actually, same goes for Company completion, which gives

```
error in process sentinel: Bad string format: "doesn't start with `\"'!"
```

**Comment by zonuexe** [comment]
@zilti 
Thank you for reporting.
It looks like Phpactor has crashed. Can you share the contents of the `*Phpactor Output*` buffer with us?

**Comment by zilti** [comment]
I can, here it is:

```
PHP Warning:  Xdebug MUST be loaded as a Zend extension in Unknown on line 0
PHP Warning:  Module 'xdebug' already loaded in Unknown on line 0
PHP Warning:  Xdebug MUST be loaded as a Zend extension in Unknown on line 0
{"version":"1.0.0","action":"echo","parameters":{"message":"<unknown> <unknown>"}}
```

**Comment by zonuexe** [comment]
@zilti 
Just that is a hint about the problem your PHP environment has.  Xdebug is not set up correctly in the PHP environment.  If you need Xdebug, set it up properly.  If you don't need Xdebug, you can find the configuration file from `php --ini` and comment out the xdebug line.

See this article for details https://xdebug.org/docs/install

**Comment by zilti** [comment]
That indeed fixed it, even though PHP only shows it as a warning, not error. I already had it configured to load as Zend extension, but additionally had the php.ini entry. Fixed now. Thanks!
