### ISSUE TITLE
How to install?

### ISSUE THREAD

**Issue by dantleech** [emacs-php/phpactor.el#21]
Hi, am trying to get this running in Spacemacs, but as I only used Emacs for about 3 hours, I am struggling :)

Can you suggest the minimum I need to do to get `phpactor.el` running in vanilla Spacemacs? (or maybe suggest a similar project with a docmented installation guide?)

Thanks!

**Comment by ejmr** [comment]
Not a Spacemacs user but maybe there is useful info here:

https://github.com/syl20bnr/spacemacs/tree/master/layers/%2Blang/php

**Comment by kermorgant** [comment]
Hello,

I would suggest spacemacs + php mode where php-mode is installed from a custom private layer. In this way, you avoid interferences from other php related stuff coming from the default php layer.

That's the path I've chosen and you can see [how I defined my layer here](https://github.com/kermorgant/helpers/tree/master/spacemacs/.spacemacs.d/layers/myphp).

To enable it, declare it in .spacemacs ([see reference to myphp here](https://github.com/kermorgant/helpers/blob/master/spacemacs/.spacemacs)) and copy or symlink it into ~/.emacs.d/private 
![image](https://user-images.githubusercontent.com/10561580/40572266-175a01c4-60b0-11e8-830e-fcd096ff1358.png)

You can also have a look at the doc about private layers [here](https://github.com/syl20bnr/spacemacs/blob/master/doc/DOCUMENTATION.org#managing-private-configuration-layers)

**Comment by dantleech** [comment]
Brilliant, got it working, thanks both :)
