### ISSUE TITLE
update company-phpactor following recent phpactor completion changes

### ISSUE THREAD

**Issue by kermorgant** [emacs-php/phpactor.el#42]
see https://github.com/phpactor/completion/pull/10

quoting phpactor's author

> adds `class_import` key to the suggestions, deprecates `'info'` in favour of `short_description` and removed the vim specific types, e.g. `t`, `m` and `c`, so you have `method`, `constructor`, `class`, `variable`, etc.

**Comment by dantleech** [comment]
_could_ be removed in 0.10.0 (release after next).

**Comment by kermorgant** [comment]
fixed by upcoming #43
