### ISSUE TITLE
Bump version 0.1.0

### ISSUE THREAD

**Issue by zonuexe** [emacs-php/phpactor.el#47]
Since some problems have been fixed since 0.0.2, we will release it as `0.0.3` or `0.1.0`.

----------

## Changelog

[Keep a Changelog](https://keepachangelog.com/) principle

### Add

 * Implement actions
    *  RPC action `import_class` #34 
    *  RPC action `close-file`  #39
    *  Editor action `collection` #39 

### Changed

 * Replace `company-grab-symbol` by specific company-phpactor--grab-symbol #29 
 * Automatically add appropriate `use` statement after class completion #34

### Fixed

 * Alter `php-mode'`s syntax table on the fly to use correct completion prefix #29
 * Fix completion and goto definition when file contains multi-byte chars #40 #46 
 * Fix `move_class` RPC action #36 #39

**Comment by zonuexe** [comment]
@kermorgant Can you fill in the explanation about Changelog issue?

---

And since you contributed to many parts of this package, you can add your name as a collaborative author. If you are interested in that, please add your name before releasing.

For example:

```patch
diff --git a/company-phpactor.el b/company-phpactor.el
index f5648de..d70bbd5 100644
--- a/company-phpactor.el
+++ b/company-phpactor.el
@@ -3,6 +3,7 @@
 ;; Copyright (C) 2018  Friends of Emacs-PHP development

 ;; Author: Martin Tang <martin.tang365@gmail.com>
+;;         Mikael Kermorgant <your-email@example.com>
 ;; Created: 18 Apr 2018
 ;; Version: 0.0.2
 ;; Keywords: tools, php
diff --git a/phpactor.el b/phpactor.el
index af2bb45..2e8c9e8 100644
--- a/phpactor.el
+++ b/phpactor.el
@@ -3,6 +3,7 @@
 ;; Copyright (C) 2018  Friends of Emacs-PHP development

 ;; Author: USAMI Kenta <tadsan@zonu.me>
+;;         Mikael Kermorgant <your-email@example.com>
 ;; Created: 8 Apr 2018
 ;; Version: 0.0.2
 ;; Keywords: tools, php
```

**Comment by kermorgant** [comment]
@zonuexe done

Thanks for the authorship, I'll add that in a future commit

**Comment by zonuexe** [comment]
@kermorgant Thanks a lot!

**Comment by zonuexe** [comment]
[Version 0.1.0](https://github.com/emacs-php/phpactor.el/releases/tag/0.1.0) released.
