### ISSUE TITLE
goto definition error when looked up method does not exist

### ISSUE THREAD

**Issue by kermorgant** [emacs-php/phpactor.el#5]
I invoked phpactor-goto-definition on setDeadLine method, on a codeline like this 

```php
                $project->setDeadLine(new \DateTime('+ 2 months'));

```
There is a typo error, the "setDeadline" method does not have an uppercase L, so I got this error 

```text
apply: Symbol’s function definition is void: phpactor-action-error
```
I guess this is already on the todolist, I hope you don't mind me reporting minor issues like this.

**Comment by zonuexe** [comment]
@kermorgant  Thank you! I apologize for missing your pointing.
